title: Adam Twardoch’s TTS training data
description: Some training data for text-to-speech
baseurl: "/"
url: "https://twardoch.github.io/text-to-speech-data"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
kramdown:
  parse_block_html: true
heading_anchors: true
collections:
  pages:
    output: true
    permalink: /:path/
permalink: pretty

search_enabled: true

search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

footer_content: "Compiled by Adam Twardoch"
